### ISSUE TITLE
怎样使用您提供的在grafana中配置V2Ray Dashboard的json，我设置了默认的Data Sources，也显示了所有的v2ray-exporter，但是一些详细参数却没有数据，是不是还要设置什么参数之类的？

### ISSUE THREAD

**Issue by vampire725** [wi1dcard/v2ray-exporter#2]
![image](https://user-images.githubusercontent.com/42635359/82313619-2da74780-99fb-11ea-9bad-fa1d29306e08.png)

**Comment by gpp0725** [comment]
![image](https://user-images.githubusercontent.com/42635359/82313540-15372d00-99fb-11ea-95d8-93b197acad1c.png)

**Comment by wi1dcard** [comment]
你好。

请检查是否按照本项目 README 或 <https://guide.v2fly.org/advanced/traffic.html> 配置好了 V2Ray 相关选项。

**Comment by vampire725** [comment]
嗯，，昨天有测试使用您在Grafana lab的发布的[json文件](https://grafana.com/grafana/dashboards/11545) ，然后是可以正确显示结果的；
而使用Github版本的则无法显示；
初步对比两个版本的json文件，感觉是修改后的expr表达式无法正确获取instance导致的。
因为对Prometheus QL不够熟悉，到底什么原因造成的还不是很清楚呢。

**Comment by wi1dcard** [comment]
感谢对此问题的持续关注。

请问你使用的 Grafana 版本是？我目前测试的 Grafana 版本是 6.7.1，Master 分支的最新面板 JSON 工作正常。

**Comment by wi1dcard** [comment]
Closed due to inactive. Please feel free to reopen it if you got more information.
