### ISSUE TITLE
exporter 在 grafana.com 的面板没有获得与仓库中一样的更新

### ISSUE THREAD

**Issue by unknowndevQwQ** [wi1dcard/v2ray-exporter#4]
在这两天我注意到了在仓库中的 dashboard.json 有更新，但是想导入 grafana.com 上的 id 发现它并没有与仓库的一起更新

其实本来应该是不需要这个 issue 的，不过我并没有在 bio 与留下的站点中找到任何联系信息
见谅

**Comment by wi1dcard** [comment]
多谢提醒。

此处确实是有意不保持最新的。由于 Grafana.com 暂时没有提供相关 API 供 CI 自动推送最新版本的 dashboard，因此只好将最新的仪表盘存放在 GitHub。

目前已经在 README 中提到此问题，并将最新版的 dashboard 推送到了 Grafana.com。
