### ISSUE TITLE
关于面板有部分没有显示数据

### ISSUE THREAD

**Issue by peytonyip** [wi1dcard/v2ray-exporter#6]
1. 问题：在导入面板后，发现部分数据没有显示出来
<img width="1872" alt="1" src="https://user-images.githubusercontent.com/28802445/86793453-0cc7ae00-c09e-11ea-9386-fdba1d69b26e.png">

2. Grafana版本：7.0.5
3. 目前的解决方法：实际数据是有的，测试调整PromQL后，就有数据了
   把没有数据那些地方的`instance="$instance"`，调整为`instance=~"$instance"`
调整前：
<img width="1919" alt="2" src="https://user-images.githubusercontent.com/28802445/86793278-e0ac2d00-c09d-11ea-8e93-6ae0a368fc1e.png">

调整后：
<img width="1918" alt="3" src="https://user-images.githubusercontent.com/28802445/86793314-e99cfe80-c09d-11ea-8b34-f89932c9a3ba.png">

4. 另外还有个疑问，就是两个Total Bandwidth显示的内容看着像是重复了？
<img width="1867" alt="4" src="https://user-images.githubusercontent.com/28802445/86793822-6def8180-c09e-11ea-975a-8a9331506a60.png">

**Comment by wi1dcard** [comment]
你好，很高兴听到你的反馈。

关于问题一，目前 [最新版本的 Grafana dashboard](https://github.com/wi1dcard/v2ray-exporter/blob/master/dashboard.json) 似乎没有 `instance="$instance"` 的 Query，请问你导入的面板是什么来源？

关于问题二，根据你的截图，目前你只有一个 instance。如果存在多个 instances，那么图示下方的 Total Bandwidth 将会存在多个副本，每个副本展示各自 instance 的 Total Bandwidth。

**Comment by peytonyip** [comment]
导入的面板是从 [https://grafana.com/grafana/dashboards/11545](url) 下载的，也有试过 github 这里的，都是一样的结果
在 github 的 json 里面，可以搜索出 `instance=\"$instance\"` ，不知道是不是你说的 Query
![5](https://user-images.githubusercontent.com/28802445/86899977-4c91a280-c13d-11ea-8ed9-854eb9761e73.png)

**Comment by wi1dcard** [comment]
感谢你的反馈，是我搜索时疏忽了，的确有 `instance=\"$instance\"`。我稍后修复一下，多谢！
