### ISSUE TITLE
项目附带的 dashboard 没有 outbounds

### ISSUE THREAD

**Issue by unknowndevQwQ** [wi1dcard/v2ray-exporter#7]
是的，现在 outbounds 流量也可以统计了
但是应该它怎么放呢？（这边由于没有这个需求就没动手（逃）

**Comment by wi1dcard** [comment]
2333，请问是 V2Ray 或是 V2Fly 的哪个版本？

**Comment by unknowndevQwQ** [comment]
> 2333，请问是 V2Ray 或是 V2Fly 的哪个版本？

从 4.26 开始可以对 outbounds 进行统计

**Comment by wi1dcard** [comment]
已适配并新增相关文档，新版本：[v0.5.0](https://github.com/wi1dcard/v2ray-exporter/releases/tag/v0.5.0)。
